# Generated by Django 2.1.7 on 2020-06-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ista', '0005_auto_20200531_1954'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
